export const sampleParts = [
  {
    id: 11111,
    name: 'Need more time',
    description: '',
    messages: ['You need more time to deadline? No problem, I can help add more time'],
    type: 'question',
    questions: [
      {
        id: 221,
        name: 'Add one day +',
        description: '',
        messages: ['Good. {Current Task} will added extra one day to deadline.', 'Bye.'],
        type: 'question',
        questions: [],
        color: 'yellow',
      },
      {
        id: 222,
        name: 'Add two day +',
        description: '',
        messages: ['Good. {Current Task} will added extra two day to deadline.', 'Bye.'],
        type: 'question',
        questions: [],
        color: 'orange',
      },
      {
        id: 333,
        name: 'Add more days',
        description: '',
        messages: ['You need more time to deadline of {Current Task} ? Please input days count what you need'],
        type: 'question',
        questions: [],
        color: 'red',
      },
    ],
    color: 'blue',
  },
  {
    id: 5545,
    name: 'Send email',
    description: '',
    messages: ['You need send email to:'],
    type: 'question',
    questions: [
      {
        id: 3433,
        name: 'Administrator',
        description: '',
        messages: ['Please send e-mail to administrator: admin@email.com'],
        type: 'question',
        questions: [],
        color: 'yellow',
      },
      {
        id: 2342,
        name: 'Owner',
        description: '',
        messages: ['Please send e-mail to owner: owner@email.com'],
        type: 'question',
        questions: [],
        color: 'orange',
      },
    ],
    color: 'violet',
  },
];

export const sampleBots = [
  {
    id: '0000X00000',
    action: '/demoBot',
    name: 'Demo Bot',
    messages: ['Hi {User Name}, I`m demonstration Bot', 'You have problem with {Current Task} ? Ok. I can help you.'],
    description: 'Simple Demonstration Bot',
    questions: [
      {
        id: 11111,
        name: 'Need more time',
        description: '',
        messages: ['You need more time to deadline? No problem, I can help add more time'],
        type: 'question',
        questions: [
          {
            id: 221,
            name: 'Add one day +',
            description: '',
            messages: ['Good. {Current Task} will added extra one day to deadline.', 'Bye.'],
            type: 'question',
            questions: [],
            color: 'yellow',
          },
          {
            id: 222,
            name: 'Add two day +',
            description: '',
            messages: ['Good. {Current Task} will added extra two day to deadline.', 'Bye.'],
            type: 'question',
            questions: [],
            color: 'orange',
          },
          {
            id: 333,
            name: 'Add more days',
            description: '',
            messages: ['You need more time to deadline of {Current Task} ? Please input days count what you need'],
            type: 'question',
            questions: [],
            color: 'red',
          },
        ],
        color: 'blue',
      },
      {
        id: 111112,
        name: 'Task details',
        description: '',
        messages: ['Ok need more details about {Current Task} ? Ok, choice kind of details'],
        type: 'question',
        questions: [
          {
            id: 3333,
            name: 'Need full description about task',
            description: '',
            messages: ['Ok, I say {Current Task} owner about this problem', 'Bye.'],
            type: 'question',
            questions: [],
            color: 'pink',
          },
          {
            id: 4444,
            name: 'Need screenshots or pictures',
            description: '',
            messages: ['Ok, I say {Current Task} owner what you wait more information', 'Bye.'],
            type: 'question',
            questions: [],
            color: '',
          },
        ],
        color: 'green',
      },
    ],
    type: 'Greeting',
  },
];
